// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2Mc4152M48PgIoZw0MeyDUcszNifaIYg',
    appId: '1:508773933300:web:43035eb22d48457da3fea1',
    messagingSenderId: '508773933300',
    projectId: 'inteliiclass',
    authDomain: 'inteliiclass.firebaseapp.com',
    storageBucket: 'inteliiclass.firebasestorage.app',
    measurementId: 'G-EPRB9HVQXB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBM5HnHb7Z8let3Egogt_DvPDC01qunrRg',
    appId: '1:508773933300:android:b3cca4552fc820b9a3fea1',
    messagingSenderId: '508773933300',
    projectId: 'inteliiclass',
    storageBucket: 'inteliiclass.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_VMxHoSSJ3KmtTx3Oke2BOaZVuHSSFBg',
    appId: '1:508773933300:ios:bad53172b108966aa3fea1',
    messagingSenderId: '508773933300',
    projectId: 'inteliiclass',
    storageBucket: 'inteliiclass.firebasestorage.app',
    iosBundleId: 'com.example.inteliiclass',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_VMxHoSSJ3KmtTx3Oke2BOaZVuHSSFBg',
    appId: '1:508773933300:ios:bad53172b108966aa3fea1',
    messagingSenderId: '508773933300',
    projectId: 'inteliiclass',
    storageBucket: 'inteliiclass.firebasestorage.app',
    iosBundleId: 'com.example.inteliiclass',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2Mc4152M48PgIoZw0MeyDUcszNifaIYg',
    appId: '1:508773933300:web:8a4d68fa1133428ca3fea1',
    messagingSenderId: '508773933300',
    projectId: 'inteliiclass',
    authDomain: 'inteliiclass.firebaseapp.com',
    storageBucket: 'inteliiclass.firebasestorage.app',
    measurementId: 'G-GJVWZSKQ2R',
  );
}
